### PR TITLE
Allow timestamps to be submitted

### PR DESCRIPTION
**Pull request by thetaylor82**
I don't see a reason why timestamps should fail. A quick check for timestamps resolves the issue.

### CODE REVIEW

**Comment by jimmiw** [comment]
i'll just do some more testing before adding this. Thanks in advance :)

**Comment by jimmiw** [comment]
not using this, since DateTime can do the "math" for me. 
See #29 for more info if needed.
Thanks though

**Comment by thetaylor82** [comment]
Makes no sense. This basically doubles up the effort and likelihood of error by converting a timestamp to a string using datetime and then back again using strtotime!

**Comment by jimmiw** [comment]
I dont really see the problem...
You are taking a timestamp, sending it to a datetime object, then formatting it back...

I don't really use timestamps, since I store dates in the database using GMT. This also helps me with timezones, as I take the GMT time into DateTime, convert it to my timezone, then pass it to timeago.

This makes the use-case you have, unimportant to me.

**Pull request closed without merging**
